<meta name="description" content="Take a video or (tiled) background of any resolution, and project information onto that using any weblanguage you want. Written in a style simple enough for children to learn from.">
<?php
    require_once(dirname(__FILE__).'/../NicerAppWebOS/boot.php');
    global $naWebOS;
    global $naURLs;
    //$src = $naWebOS->codePath.'/../../domains/'.$naWebOS->domainFolder.'/domainConfig/pageHeader.php'; echo $src; var_dump(file_exists($src)); exit();
    require_once ($naWebOS->codePath.'/../domains/'.$naWebOS->domainFolder.'/domainConfig/pageHeader.php');
?>

    <iframe loading="lazy" defer="" artist="Skyla Reeze" song="All he said" width="560" height="315" src="https://www.youtube.com/embed/9uCJiPSsMvk?si=XDiiyF04qzSLrxJi" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/ppxE19VzyfE?si=Tq4HQJSd3Hz0MZ0w" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/qwfz21EkW9I?si=j-v68rYctgNLIm5i" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/Lf-rEslupnY?si=PMcC0wuwq3KNAuYN" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/Qt6Lkgs0kiU?si=Fc74R2TpwtwDT9VS" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/2AMnn2KFNas?si=3yZwHfhwlxNLLxRF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>

    <iframe loading="lazy" defer="" artist="Skyla Reeze" song="U and I" width="560" height="315" src="https://www.youtube.com/embed/YZRqT2hbXLE?si=0ZfeUBPCazQqLAHF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/yC-wslvmf4I?si=Eldr73Lqu602JoX4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/GbEI-AiOuAo?si=dLhkKwUI8kflH4af" title="YouT    ube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/zazZXLj3h38?si=4IC41ilh5e65BFNE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/dxBYuE_qSt8?si=-UMOt3jeBdGL1tBl" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>

    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/8bxZ78itTPc?si=Paace06biisnIfCA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/NeO8IiS996k?si=KDNjB3MCnlWIlWUJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/SPhhPFYn_n0?si=f_lXyRwvej-vMKQn" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/eMXKp3h3qDI?si=nioX7vJKrgEcYdCQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/pKQ2m12_1So?si=aXhUv0m3_QyCYHeP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/w4sdZ0OfBs8?si=6Wub1bAH-p747yiA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Kraantje pappie" song="Pompen" width="560" height="315" src="https://www.youtube.com/embed/qlaki1uw0Hc?si=9B6bQPGYhjzilSYV" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/rdXbpp9G5KA?si=LZA8tmxw5OmFVJDV" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/BcxsYZMC1dw?si=e-oEeWLUHzC0zhGo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/SNc0EasxBqM?si=CWZMvNf3B41KvLIh" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Aria Voss" song="Emotional Uplifting Trance Mix Vol.1 | 1 Hour Female Vocal Trance" width="560" height="315" src="https://www.youtube.com/embed/6kfNYfZ6IPY?si=0lQO-rHQHDzkE611" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Skyla Reeze" song="Under my skin" width="560" height="315" src="https://www.youtube.com/embed/U3CbVfeO1I8?si=xKEQz-Ca-hlkBgE-" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Suzanne en Freek" song="Goud" width="560" height="315" src="https://www.youtube.com/embed/MlBQ8-B99iw?si=oikeIjJrVzk2uAss" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Suzanne en Freek" song="Zoute Landen" width="560" height="315" src="https://www.youtube.com/embed/N0OLEgc-Glk?si=v5OIYKw504oPBI1d" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe artist="Emma Hewitt" width="560" height="315" src="https://www.youtube.com/embed/dpakM-dIkrg?si=YeFECpMY47DSo2CP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="DBZ AMV XXG GMV" song="Who we are" width="560" height="315" src="https://www.youtube.com/embed/GLDUNJrTmzE?si=rIwYxsC6ScSITPkF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Jewel" song="Stand" width="560" height="315" src="https://www.youtube.com/embed/ELFaFkpBVIs?si=ZLxTOYSsabVXKFpe" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="West Coast AI" song="Static on the line" width="560" height="315" src="https://www.youtube.com/embed/UqjenKMEczA?si=AL8FJeiZUtqbUIT2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Ellie Goulding" song="Guns and horses" width="560" height="315" src="https://www.youtube.com/embed/IDwbHeR0UYc?si=Xuiolko1Zr6xm0kj" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/1mb3cXHH6QQ?si=t_WA-4de4btgdDu-" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>


    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/uyTmloly1t8?si=C9tZ7LS77vwcS-ns" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/gLMjBM_aXJ0?si=G3VEC6TwZtYGrxWm" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Sabaton" song="Ghost division" width="560" height="315" src="https://www.youtube.com/embed/HeHzqAv5yns?si=lXXt9kck9HmdsT8h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/7wHPskHEj7k?si=1Cw5jrWCR0ZLGeU7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/ZgfCUxFE7XA?si=1QiM0CGilFpEADdf" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/9au0yfVdt7o?si=nWmKMNMC-1cK-lBp" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/X-2yuGgp_U8?si=EJvYf1lEGGCVNGbI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/7iNbnineUCI?si=KVLX0Ws3wsYxPMqs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Katy Perry" song="Part of me" width="560" height="315" src="https://www.youtube.com/embed/uuwfgXD8qV8?si=UxzV3NQ9SP_N8gUP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Froukje" song="Groter dan ik" width="560" height="315" src="https://www.youtube.com/embed/IUGFn7wQSlM?si=yApstcOATRZuC8UX" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Sabaton" song="Ghost in the trenches" width="560" height="315" src="https://www.youtube.com/embed/wbkEFIVXLNw?si=IaMEDXFsW3QXpF13" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artists="Best remixes" song="Best remixes of popular songs in 2019" width="560" height="315" src="https://www.youtube.com/embed/A0bTOQn_XPY?si=cmk7y-20iADkhW2h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Disturbed" song="Bad man" width="560" height="315" src="https://www.youtube.com/embed/fpUpVznI4Yc?si=bpxo6VSp5MPp8D6O" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Disturbed" song="No more" width="560" height="315" src="https://www.youtube.com/embed/eQji1bEXwc0?si=Vy_ldalfCdnlQOV0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/v57939j8Bsk?si=Mqj32SFZdVJ5Iu3w" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>



    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/V8ab53R14Lk?si=5HKlVlX7EK6on5V1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/d7EPbt-hwjw?si=7uLuMIRAliY63HYa" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/AmBGTan1K74?si=Ctif5xzlMEo6jyKR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/_PSBMEu3y_k?si=KKKgcJqC0YGjiv42" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/zx5Q1pOgDRI?si=oPlCl14Xz2Dhwd5g" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/l7mnTGVYY9Q?si=auC722snX_PgP0k0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>

    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/SjmZ5v3xTeA?si=omRwFe6GwUvp3myi" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Premium Music HQ" song="Lost Souls" width="560" height="315" src="https://www.youtube.com/embed/45kf3GiKOP8?si=lAxmOfOADfMBPD2o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="TranceLuuvers" song="Chillout mix 2015 Vol. 2" width="560" height="315" src="https://www.youtube.com/embed/BBmy0Y7WaJI?si=QdNYE9EcVctCghap&amp;start=4460" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>

    <iframe loading="lazy" defer="" artist="Shinedown" song="Devour (GMV)" width="560" height="315" src="https://www.youtube.com/embed/h42PQf4xH9U?si=z4XbXnaYXTrjtaOD" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="EDM New Style" song="In the fire (GMV)" width="560" height="315" src="https://www.youtube.com/embed/QrVJ-Kiif1E?si=uk6DPfYjeXNlcF1w" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Best of Ninja Tracks" song="Volume 1" width="560" height="315" src="https://www.youtube.com/embed/Ob9XH--7-GY?si=Xxat-ViZIHCR9ZlX" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Christine O'Donnell autotune" song="I'm not a witch!" width="560" height="315" src="https://www.youtube.com/embed/44mqiBrB0zI?si=l34JJyizCeW3rB4U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Ghost in the shell" song="Opening intro" width="560" height="315" src="https://www.youtube.com/embed/8Pk9yNy-kig?si=Zmxm9W3b9VK_ja2_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="2Shades" song="What doesn't kill you makes you stronger remix" width="560" height="315" src="https://www.youtube.com/embed/Og_hgmA6AmQ?si=WFvKPsXvOGkITqiQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Killers" song="My own soul's warning" width="560" height="315" src="https://www.youtube.com/embed/4go_DzY8wHc?si=d5iz_wDxBgKR_v3V" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Kelly Clarckson" song="Stronger" width="560" height="315" src="https://www.youtube.com/embed/cRM70Jw7F4M?si=Npd8dmuuX1fyqHGZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Umbrella corp" song="Resident Evil opening scene" width="560" height="315" src="https://www.youtube.com/embed/7zuDZrySShA?si=RR4WMetbmUMukYYK" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="EDM New Style" song="Phoenix (GMV)" width="560" height="315" src="https://www.youtube.com/embed/2x2OPY9Ggto?si=30gxWZEVm_mMS9YA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Cypress Hill" song="Gorillaz" width="560" height="315" src="https://www.youtube.com/embed/V5fAAtIfrCA?si=NR1Okzqw2mZZ0hy_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>

    <iframe loading="lazy" defer="" artist="Cypress Hill" song="3 hours Best Of 2026" width="560" height="315" src="https://www.youtube.com/embed/rRJMzPICpwM?si=LTk40QPCPk6P7DXN" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" width="560" height="315" src="https://www.youtube.com/embed/DpqFEwGmPII?si=yqCy7vdLhRkLopjg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>

    <iframe loading="lazy" defer="" artist="Skyla Reeze" song="Piece of me" width="560" height="315" src="https://www.youtube.com/embed/e6vKphKPFaQ?si=xh9np21136rIGuu3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Survivor" song="Eye of the tiger (remix by Laura Amara)" width="560" height="315" src="https://www.youtube.com/embed/_uQLWRWD-NQ?si=l0CbmEVo1Uu2OVl5" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Gabre Ponte vs Jerome" song="Lonely (Official lyric video)" width="560" height="315" src="https://www.youtube.com/embed/HzNJt_5sKHc?si=n0PBMzy6DnMujsCK" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Parov Stelar" song="Chambermaid swing (Doc-Terry's video club mix)" width="560" height="315" src="https://www.youtube.com/embed/QN4tPpJngyM?si=x3lp4gBHQq_PxRyS" title="YouTube video player" frameborder="0" allow="accelerometer;  autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe loading="lazy" defer="" artist="Jaruss11" song="Best remix of Requim for a Dream" width="560" height="315" src="https://www.youtube.com/embed/7e0YBeSIcKE?si=CHyfD5nt7-eYnCE5" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/WV1c1hXMRtY?si=umrpBjrKI1e0PKn8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe artist="Amy Macdonald" song="This is the life" width="560" height="315" src="https://www.youtube.com/embed/iRYvuS9OxdA?si=S1cmSUVGh2LdOHqm" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe artist="Skyla Reeze" song="Now we are free" width="560" height="315" src="https://www.youtube.com/embed/t4Wl3V-1GnQ?si=mq-T6oWGDkg5-96Y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe artist="Garret John" song="All that love can do" width="560" height="315" src="https://www.youtube.com/embed/JbvdIpMaYEM?si=MFqNGKhYjdLkHjlf" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe artist="Ellie Goulding" song="Lights" width="560" height="315" src="https://www.youtube.com/embed/0NKUpo_xKyQ?si=JtLTaMlA33coQNPW" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/GiDnYmCU9Y0?si=uSacJRDWYUyrx1RF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/sqSA-SY5Hro?si=IH54XZpWaP0HEtVM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/ppxE19VzyfE?si=eDQBxKyq0Sl_9G4L" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/t0heT04DLOU?si=zBbBk34oYgYmV0yw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/6uoFh57_SEg?si=giag_bb2rZqTbeJP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/tGw11VwJFJA?si=e_wGEU7i7euJ2axA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/erf0m_eO8Ho?si=ETuZrxWo-xakcPZN" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/8yVFKFqJDd4?si=jyVo-Pixw_xoOEGI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/oRzjkd6pjEs?si=48AKRGI6SPyyk8th" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/U3_i9sPs4qs?si=k9k78Il2fWqIp8-v" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/yFgdfG7z5Ho?si=EXdBB3jvVRFh1qN6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/s5212tWdhlY?si=TNGzJbg5T07JGut4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/utSupFnnL7I?si=yWP75MoDxNWhiW48" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
